### ISSUE TITLE
Add Discord server info to the docs

### ISSUE THREAD

**Issue by courtland** [JonasAlfredsson/docker-kea#4]
While reviewing PR #2 I realized I would like to participate in the "official Discord channel", but for the life of me I cannot find where this is. Could you add any Slack/Discord/etc channels to the docs that you propose we have discussions on? Thanks!

**Comment by courtland** [comment]
Thanks for clarifying! I didn't notice it in your profile, thought maybe you were talking about the kubernetes Discord, or one from ISC that I wasn't able to find. Makes sense to leave it as is to me. Cheers!

**Comment by JonasAlfredsson** [comment]
Yeah I wish, I am just some random dude on the internet that apparently managed to get at least 7 people interested in this container. It will probably require a bit more before it is recognized in these other places ;)
