### ISSUE TITLE
push kea-dhcp4-ha:2.6.1 tag

### ISSUE THREAD

**Issue by jdelkins** [JonasAlfredsson/docker-kea#64]
Hi, the `2.6.1` and `2.6.1-alpine` image tags seem to be missing for `kea-dhcp4-ha` from docker hub, can you please check your ci pipeline and/or push these? Thank you for this build!

**Comment by jdelkins** [comment]
Hi, I just realized you now include the ha hooks in the main image -- closing issue, sorry for noise

**Comment by JonasAlfredsson** [comment]
Oh right, those images might still be present on Dockerhub. I will remove them to not confuse. 

Thanks for bringing this to my attention :)
